#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other POSIX shell available, most
#       probably one of these fixes will help:
#         - For 5.0+, run "bash".
#
#   (2) The GRADLE_HOME environment variable is not required to run this script,
#       but will provide faster startup if set.
#
#   (3) To enable debug mode run with this environment variable set to true:
#
#       GRADLE_DEBUG=true ./gradlew <task>
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_PATH=$( cd "${APP_PATH%/*}" && pwd -P )/"${APP_PATH##*/}"
else
    APP_PATH=$( cd "${APP_PATH%/*}" && pwd -P )/"${APP_PATH##*/}"
    # For Cygwin or MSYS, switch paths to Windows format before running java
    case "$UNAME" in
        CYGWIN*) APP_HOME=$(cygpath --path --mixed "$APP_HOME") ;;
        MSYS*) APP_HOME=$(echo "$APP_HOME" | sed 's|\\|/|g') ;;
    esac
fi

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" "$@"
